/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
/**
 *  Package and Import Specifications.
 */

import java_cup.runtime.*;

/**
 *  Usercode Components.
 */

parser code {:
    // Connect this parser to a scanner!
    Scanner s;
    Parser(Scanner s){ this.s=s; }
:}

/* define how to connect to the scanner! */

scan with {: return s.next_token(); :};

/**
 *  Symbol Lists.
 */

/* Terminals (tokens returned by the scanner). */

terminal String     CONCAT, LPAREN, RPAREN, LBRACE, RBRACE, COMMA;
terminal String     EQ, PREF, SUFF, REVERSE;
terminal String     IF, ELSE;
terminal String     IDENTIFIER, STRING;

/*  Non terminals */
/* All the rules of my grammar are non-terminals, I am writing them
   in the order they are being expanded in my grammar */

non terminal String   goal, startPoint, functionDefinition, functionDefArgs, continue, exprList;
non terminal String   functionCall, functionCallArgs, conditional, exprCon, prefix, suffix, equal, reversion, concatenation;

/**
 *  Precedence Declarations,
 *  based on the project's specifications.
 */

precedence left IDENTIFIER;
precedence left IF;
precedence left CONCAT;
precedence left REVERSE;


/**
 *  The Grammar Rules for our parser.
 */

/* The starting point of our grammar */

goal ::= startPoint:start                                                                                                               {: System.out.println(start); :}
       ;

/* 
 * this breaks the program into two sections,
 * the function definitions
 * and the function calls, or other expressions
 * so for now, the second section is called continue
*/ 

startPoint          ::= functionDefinition:funDef startPoint:start                                                                      {: RESULT = funDef + " " + start; :}
                      | continue:cn                                                                                                     {: RESULT = cn; :}
                      ;

/*
 * Let's further analyze the fuction definitions section.
 * It has to be like this: id ( args ) { exprList }
 * and without args can be possible
*/

functionDefinition  ::= IDENTIFIER:id LPAREN:lpar functionDefArgs:funcDefArgs LBRACE:lbrac exprList:expL RBRACE:rbrac                   {: RESULT = id + " " + lpar + " "  + funcDefArgs + lbrac + "\n" + expL + "\n" + rbrac + "\n\n"; :}
                      | IDENTIFIER:id LPAREN:lpar RPAREN:rpar LBRACE:lbrac exprList:expL RBRACE:rbrac                                   {: RESULT = id + " " + lpar + " " + rpar + "\n" + lbrac + "\n" + expL + "\n" + rbrac + "\n\n"; :}
                      ;

/* 
* The arguments a function can take.
* It can be arg1, arg2, arg3
* Or one argument only, arg1
* I added here the right parenthesis
* to solve some abiguity problems that I had
*/

functionDefArgs     ::= IDENTIFIER:id COMMA:com functionDefArgs:funcDefArgs                                                             {: RESULT = id + " " + com + " " + funcDefArgs; :}
                      | IDENTIFIER:id RPAREN:rpar                                                                                       {: RESULT = id + " " + rpar + "\n"; :}
                      ;

/*
* The second segment of my program.
* It includes function calls and other expressions.
* Let's analyze it!
*/

continue            ::= exprList:expL continue:cn                                                                                       {: RESULT = expL + "\n" + cn; :}
                      | exprList:expL                                                                                                   {: RESULT = expL; :}
                      ;

/*
* All the expressions that are allowed
* in the second segment of our program
*/

exprList            ::= conditional:cond                                                                                                {: RESULT = cond; :}
                      | concatenation:concat                                                                                            {: RESULT = concat; :}
                      | reversion:rev                                                                                                   {: RESULT = rev; :}
                      | functionCall:funcCall                                                                                           {: RESULT = funcCall; :}
                      | STRING: str                                                                                                     {: RESULT = str; :}
                      | IDENTIFIER:id                                                                                                   {: RESULT = id; :}
                      ;

/*
* At last we needed to break the allowed
* expressions because of ambiguity reasons.
* One rule was not allowed to access some expressions
* and when I made them two I had biguity problems.
* So here is the continuation of exprList, productions.
*/

/* productions         ::= functionCall:funcCall                                                                                        {: RESULT = funcCall; :}
                      | STRING: str                                                                                                     {: RESULT = str; :}
                      | IDENTIFIER:id                                                                                                   {: RESULT = id; :}
                      ;
*/

/*
* The grammar rule about the calls of the functions:
* function_name( function_calls/strings/identifiers, ... )
*/

functionCall        ::= IDENTIFIER:id LPAREN:lpar functionCallArgs:funcCallArgs                                                         {: RESULT = id + " " + lpar + " " + funcCallArgs; :}
                      | IDENTIFIER:id LPAREN:lpar RPAREN:rpar                                                                           {: RESULT = id + " " + lpar + " " + rpar; :}
                      ;

/*
* The arguments that function calls are allowed to have.
*/

functionCallArgs    ::= functionCall:funcCall COMMA:com functionCallArgs:funcCallArgs                                                   {: RESULT = funcCall + " " + com + " " + funcCallArgs; :}
                      | functionCall:funcCall RPAREN:rpar                                                                               {: RESULT = funcCall + " " + rpar; :}
                      | IDENTIFIER:id COMMA:com functionCallArgs:funcCallArgs                                                           {: RESULT = id + " " + com + " " + funcCallArgs; :}
                      | IDENTIFIER:id RPAREN:rpar                                                                                       {: RESULT = id + " " + rpar; :}    
                      | STRING:str COMMA:com functionCallArgs:funcCallArgs                                                              {: RESULT = str + " " + com + " " + funcCallArgs; :}    
                      | STRING:str RPAREN:rpar                                                                                          {: RESULT = str + " " + rpar; :}    
                      ;

/*
* The rule about the conditional statements
* of our language, if (...) else ...
*/

conditional         ::= IF:if1 LPAREN:lpar exprCon:expC RPAREN:rpar exprList:expL ELSE:else1 exprList:expL2                               {: RESULT = if1 + " " + lpar + " " + expC + " " + rpar + " " + expL + " " + else1 + " " + expL2; :}
                      ;

/*
* The conditionals can have inside the if parenthesis
* other conditionals or prefix/suffix/equal statements
*/

exprCon             ::= prefix:pref                                                                                                     {: RESULT = pref; :}
                      | suffix:suff                                                                                                     {: RESULT = suff; :}
                      | equal:eq                                                                                                        {: RESULT = eq; :}
                      ;

/*
* Here is the code for the prefix/suffix/equal operators.
* Also, with the reverse and concatenation of our language.
*/

prefix              ::= exprList:expL PREF:pref exprList:expL2                                                                          {: RESULT = expL + " " + pref + " " + expL2; :}
                      ;

suffix              ::= exprList:expL SUFF:suff exprList:expL2                                                                          {: RESULT = "reverse " + expL + " prefix " + "reverse " + expL2; :}
                      ;

equal               ::= exprList:expL EQ:eq exprList:expL2                                                                              {: RESULT = "if ( " + expL2 + " prefix " + expL + " ) " + expL + " else " + expL2 + " + " + expL2 + " prefix " + expL2; :}
                      ;

reversion           ::= REVERSE:rev exprList:expL                                                                                       {: RESULT = rev + " " + expL; :}
                      ;

concatenation       ::= exprList:expL CONCAT:concat exprList:expL2                                                                      {: RESULT = expL + " " + concat + " " + expL2; :}    
                      ;