/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
/**
 *  Package and Import Specifications.
 */

import java_cup.runtime.*;

/**
 *  Usercode Components.
 */

parser code {:
    // Connect this parser to a scanner!
    Scanner s;
    Parser(Scanner s){ this.s=s; }
:}

/* define how to connect to the scanner! */

scan with {: return s.next_token(); :};

/**
 *  Symbol Lists.
 */

/* Terminals (tokens returned by the scanner). */

terminal String CONCAT, LPAREN, RPAREN, LBRACE, RBRACE, COMMA;
terminal String EQ, PREF, SUFF, REVERSE;
terminal String IF, ELSE;
terminal String IDENTIFIER, STRING;

/*  Non terminals */
/* All the rules of my grammar are non-terminals, I am writing them
   in the order they are being expanded in my grammar */

non terminal String goal, startPoint, functionDefinition, functionDefArgs, continue, exprList, productions;
non terminal String functionCall, functionCallArgs, conditional, exprCon, prefix, suffix, equal, prevention, concatenation;

/**
 *  Precedence Declarations,
 *  based on the project's specifications.
 */

precedence left IDENTIFIER;
precedence left IF;
precedence left CONCAT;
precedence left REVERSE;


/**
 *  The Grammar Rules for our parser.
 */

/* The starting point of our grammar */

goal ::= startPoint:start

/* 
 * this breaks the program into two sections,
 * the function definitions
 * and the function calls, or other expressions
 * so for now, the second section is called continue
*/ 

startPoint          ::= functionDefinition:funDef startPoint:start
                      | continue:cn
                      ;

/*
 * Let's further analyze the fuction definitions section.
 * It has to be like this: id ( args ) { exprList }
 * and without args can be possible
*/

functionDefinition  ::= IDENTIFIER:id LPAREN:lpar functionDefArgs:funcDefArgs LBRACE:lbrac exprList:expL RBRACE:rbrac
                      | IDENTIFIER:i LPAREN:lpar RPAREN:rpar LBRACE:lbrac exprList:expL RBRACE:rbrac
                      ;

/* 
* The arguments a function can take.
* It can be arg1, arg2, arg3
* Or one argument only, arg1
* I added here the right parenthesis
* to solve some abiguity problems that I had
*/

functionDefArgs     ::= IDENTIFIER:id COMMA:com functionDefArgs:funcDefArgs
                      | IDENTIFIER:id RPAREN:rpar
                      ;

/*
* The second segment of my program.
* It includes function calls and other expressions.
* Let's analyze it!
*/

continue            ::= exprList:expL continue:cn
                      | exprList:expL
                      ;

/*
* All the expressions that are allowed
* in the second segment of our program
*/

exprList            ::= conditional:cond
                      | concatenation:concat
                      | reversion:rev
                      | productions:prod
                      ;

/*
* At last we needed to break the allowed
* expressions because of ambiguity reasons.
* One rule was not allowed to access some expressions
* and when I made them two I had qbiguity problems.
* So here is the continuation of exprList, productions.
*/

productions         ::= functionCall:funcCall
                      | STRING: str
                      | IDENTIFIER:id
                      ;

/*
* The grammar rule about the calls of the functions:
* function_name( function_calls/strings/identifiers, ... )
*/

functionCall        ::= IDENTIFIER:id LPAREN:lpar functionCallArgs:funcCallArgs
                      | IDENTIFIER:id LPAREN:lpar RPAREN:rpar
                      ;

/*
* The arguments that function calls are allowed to have.
*/

functionCallArgs    ::= functionCall:funcCall COMMA:com functionCallArgs:funcCallArgs
                      | functionCall:funcCall RPAREN:rpar
                      | IDENTIFIER:id COMMA:com functionCallArgs:funcCallArgs
                      | IDENTIFIER:id RPAREN:rpar
                      | STRING:str COMMA:com functionCallArgs:funcCallArgs
                      | STRING:str RPAREN:rpar
                      ;

/*
* The rule about the conditional statements
* of our language, if (...) else ...
*/

conditional         ::= IF:if LPAREN:lpar exprCon:expC RPAREN:rpar exprList:expL ELSE:else exprList:expL2
                      ;

/*
* The conditionals can have inside the if parenthesis
* other conditionals or prefix/suffix/equal statements
*/

exprCon             ::= conditional:cond
                      | prefix:pref
                      | suffix:suff
                      | equal:eq
                      ;

/*
* Here is the code for the prefix/suffix/equal operators.
* Also, with the reverse and concatenation of our language.
*/

prefix              ::= eprList:expL PREF exprList:exrpL2
                      ;

suffix              ::= exprList:expL SUFF exprList:expL2
                      ;

equal               ::= exprList:expL EQ exprList:expL2
                      ;

reversion           ::= REVERSE:rev productions:prod
                      ;

concatenation       ::= productions:prod1 concatenation:concat
                      | productions:prod1 CONCAT:concat productions:prod2
                      ;