/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
/**
 *  Package and Import Specifications.
 */

import java_cup.runtime.*;

/**
 *  Usercode Components.
 */

parser code {:
    // Connect this parser to a scanner!
    Scanner s;
    ParserJava(Scanner s){ this.s=s; }
:}

/* define how to connect to the scanner! */

scan with {: return s.next_token(); :};

/**
 *  Symbol Lists.
 */

/* Terminals (tokens returned by the scanner). */

terminal String     CONCAT, LPAREN, RPAREN, LBRACE, RBRACE, COMMA;
terminal String     EQ, PREF, SUFF, REVERSE;
terminal String     IF, ELSE;
terminal String     IDENTIFIER, STRING;

/*  Non terminals */
/* All the rules of my grammar are non-terminals, I am writing them
   in the order they are being expanded in my grammar */

non terminal String   goal, startPoint, functionDefinition, functionDefArgs, continue, exprList;
non terminal String   functionCall, functionCallArgs, conditional, exprCon, prefix, suffix, equal, reversion, concatenation;

/**
 *  Precedence Declarations,
 *  based on the project's specifications.
 */

precedence left IDENTIFIER;
precedence left IF;
precedence left CONCAT;
precedence left REVERSE;


/**
 *  The Grammar Rules for our parser.
 */

/* The starting point of our grammar */

goal ::= startPoint:start                                                                                                               {: System.out.println("public class Translated {\n" + start + "\n}"); :}
       ;

/* 
 * this breaks the program into two sections,
 * the function definitions
 * and the function calls, or other expressions
 * so for now, the second section is called continue
*/ 

startPoint          ::= functionDefinition:funDef startPoint:start                                                                      {: RESULT = funDef + "\n" + start; :}
                      | continue:cn                                                                                                     {: RESULT = "public static void main(String[] args) {\n" + cn + "}\n"; :}
                      ;

/*
 * Let's further analyze the fuction definitions section.
 * It has to be like this: id ( args ) { exprList }
 * and without args can be possible
*/

functionDefinition  ::= IDENTIFIER:id LPAREN:lpar functionDefArgs:funcDefArgs LBRACE:lbrac exprList:expL RBRACE:rbrac                   {: RESULT = "public static String " + id + "( " + funcDefArgs + "\n{\n\t return " + expL + ";\n}"; :}
                      | IDENTIFIER:id LPAREN:lpar RPAREN:rpar LBRACE:lbrac exprList:expL RBRACE:rbrac                                   {: RESULT = "public static String "+ id +"()\n{\n\t return "+ expL +";\n}"; :}
                      ;

/* 
* The arguments a function can take.
* It can be arg1, arg2, arg3
* Or one argument only, arg1
* I added here the right parenthesis
* to solve some abiguity problems that I had
*/

functionDefArgs     ::= IDENTIFIER:id COMMA:com functionDefArgs:funcDefArgs                                                             {: RESULT = "String " + id + " " + com + " " + funcDefArgs + " "; :}
                      | IDENTIFIER:id RPAREN:rpar                                                                                       {: RESULT = "String " + id + ")"; :}
                      ;

/*
* The second segment of my program.
* It includes function calls and other expressions.
* Let's analyze it!
*/

continue            ::= exprList:expL continue:cn                                                                                       {:RESULT = "System.out.println( " + expL + " );\n" + cn + " \n"; :}
                      | exprList:expL                                                                                                   {:RESULT = "System.out.println( " + expL + " );"; :} 
                      ;

/*
* All the expressions that are allowed
* in the second segment of our program
*/

exprList            ::= conditional:cond                                                                                                {: RESULT = "(" + cond + ")"; :}
                      | concatenation:concat                                                                                            {: RESULT = "(" + concat + ")"; :}
                      | reversion:rev                                                                                                   {: RESULT = "(" + rev + ")"; :}
                      | functionCall:funcCall                                                                                           {: RESULT = "(" + funcCall + ")"; :}
                      | STRING: str                                                                                                     {: RESULT = "(" + str + ")"; :}
                      | IDENTIFIER:id                                                                                                   {: RESULT = "(" + id + ")"; :}
                      ;

/*
* The grammar rule about the calls of the functions:
* function_name( function_calls/strings/identifiers, ... )
*/

functionCall        ::= IDENTIFIER:id LPAREN:lpar functionCallArgs:funcCallArgs                                                         {: RESULT = id + " " + lpar + " " + funcCallArgs; :}
                      | IDENTIFIER:id LPAREN:lpar RPAREN:rpar                                                                           {: RESULT = id + " " + lpar + " " + rpar; :}
                      ;

/*
* The arguments that function calls are allowed to have.
*/

functionCallArgs    ::= functionCall:funcCall COMMA:com functionCallArgs:funcCallArgs                                                   {: RESULT = funcCall + " " + com + " " + funcCallArgs; :}
                      | functionCall:funcCall RPAREN:rpar                                                                               {: RESULT = funcCall + " " + rpar; :}
                      | IDENTIFIER:id COMMA:com functionCallArgs:funcCallArgs                                                           {: RESULT = id + " " + com + " " + funcCallArgs; :}
                      | IDENTIFIER:id RPAREN:rpar                                                                                       {: RESULT = id + " " + rpar; :}    
                      | STRING:str COMMA:com functionCallArgs:funcCallArgs                                                              {: RESULT = str + " " + com + " " + funcCallArgs; :}    
                      | STRING:str RPAREN:rpar                                                                                          {: RESULT = str + " " + rpar; :}    
                      | conditional:cond COMMA:com functionCallArgs:funcCallArgs                                                        {: RESULT = cond + " " + com + " " + funcCallArgs; :}
                      | conditional:cond RPAREN:rpar                                                                                    {: RESULT = cond + " " + rpar; :}
                      | reversion:rev COMMA:com functionCallArgs:funcCallArgs                                                           {: RESULT = rev + " " + com + " " + funcCallArgs; :}
                      | reversion:rev RPAREN:rpar                                                                                       {: RESULT = rev + " " + rpar; :}
                      | concatenation:concat COMMA:com functionCallArgs:funcCallArgs                                                    {: RESULT = concat + " " + com + " " + funcCallArgs; :}
                      | concatenation:concat RPAREN:rpar                                                                                {: RESULT = concat + " " + rpar; :}
                      ;

/*
* The rule about the conditional statements
* of our language, if (...) else ...
*/

conditional         ::= IF:if1 LPAREN:lpar exprCon:expC RPAREN:rpar exprList:expL ELSE:else1 exprList:expL2                             {:RESULT ="("+ expC +")?("+ expL +"):("+ expL2 +")"; :}
                      ;

/*
* The conditionals can have inside the if parenthesis
* other conditionals or prefix/suffix/equal statements
*/

exprCon             ::= prefix:pref                                                                                                     {: RESULT = pref; :}
                      ;

/*
* Here is the code for the prefix/suffix/equal operators.
* Also, with the reverse and concatenation of our language.
*/

prefix              ::= exprList:expL PREF:pref exprList:expL2                                                                          {: RESULT = expL2 + ".startsWith(" + expL + ")"; :}
                      ;

reversion           ::= REVERSE:rev exprList:expL                                                                                       {:RESULT ="new StringBuilder(" + expL + ").reverse().toString()"; :}  
                      ;

concatenation       ::= exprList:expL CONCAT:concat exprList:expL2                                                                      {: RESULT = expL + " " + concat + " " + expL2; :}    
                      ;