
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141202 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserJava extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  public ParserJava() {super();}

  /** Constructor which sets the default scanner. */
  public ParserJava(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserJava(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\043\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\003\000\002\004\010\000\002\004\010" +
    "\000\002\005\005\000\002\005\004\000\002\006\004\000" +
    "\002\006\003\000\002\007\003\000\002\007\003\000\002" +
    "\007\003\000\002\007\003\000\002\007\003\000\002\007" +
    "\003\000\002\010\005\000\002\010\005\000\002\011\005" +
    "\000\002\011\004\000\002\011\005\000\002\011\004\000" +
    "\002\011\005\000\002\011\004\000\002\011\005\000\002" +
    "\011\004\000\002\011\005\000\002\011\004\000\002\011" +
    "\005\000\002\011\004\000\002\012\011\000\002\013\003" +
    "\000\002\014\005\000\002\017\004\000\002\020\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\110\000\012\015\020\016\013\020\016\021\010\001" +
    "\002\000\004\002\001\001\002\000\012\015\020\016\013" +
    "\020\016\021\010\001\002\000\030\002\ufff7\004\ufff7\006" +
    "\ufff7\010\ufff7\011\ufff7\013\ufff7\015\ufff7\016\ufff7\017\ufff7" +
    "\020\ufff7\021\ufff7\001\002\000\030\002\ufff6\004\ufff6\006" +
    "\ufff6\010\ufff6\011\ufff6\013\ufff6\015\ufff6\016\ufff6\017\ufff6" +
    "\020\ufff6\021\ufff6\001\002\000\030\002\ufff3\004\ufff3\006" +
    "\ufff3\010\ufff3\011\ufff3\013\ufff3\015\ufff3\016\ufff3\017\ufff3" +
    "\020\ufff3\021\ufff3\001\002\000\004\002\ufffe\001\002\000" +
    "\016\002\ufff8\004\051\015\020\016\013\020\022\021\010" +
    "\001\002\000\004\005\077\001\002\000\030\002\ufff4\004" +
    "\ufff4\006\ufff4\010\ufff4\011\ufff4\013\ufff4\015\ufff4\016\ufff4" +
    "\017\ufff4\020\ufff4\021\ufff4\001\002\000\030\002\ufff5\004" +
    "\ufff5\006\ufff5\010\ufff5\011\ufff5\013\ufff5\015\ufff5\016\ufff5" +
    "\017\ufff5\020\ufff5\021\ufff5\001\002\000\020\002\ufff2\004" +
    "\ufff2\005\062\015\ufff2\016\ufff2\020\ufff2\021\ufff2\001\002" +
    "\000\004\002\061\001\002\000\012\015\020\016\013\020" +
    "\022\021\010\001\002\000\030\002\uffe0\004\uffe0\006\uffe0" +
    "\010\uffe0\011\uffe0\013\uffe0\015\uffe0\016\uffe0\017\uffe0\020" +
    "\uffe0\021\uffe0\001\002\000\032\002\ufff2\004\ufff2\005\023" +
    "\006\ufff2\010\ufff2\011\ufff2\013\ufff2\015\ufff2\016\ufff2\017" +
    "\ufff2\020\ufff2\021\ufff2\001\002\000\014\006\032\015\020" +
    "\016\013\020\034\021\027\001\002\000\010\004\ufff7\006" +
    "\057\011\056\001\002\000\010\004\ufff6\006\054\011\053" +
    "\001\002\000\004\004\051\001\002\000\010\004\ufff3\006" +
    "\047\011\046\001\002\000\010\004\ufff4\006\044\011\043" +
    "\001\002\000\030\002\ufff1\004\ufff1\006\ufff1\010\ufff1\011" +
    "\ufff1\013\ufff1\015\ufff1\016\ufff1\017\ufff1\020\ufff1\021\ufff1" +
    "\001\002\000\030\002\ufff0\004\ufff0\006\ufff0\010\ufff0\011" +
    "\ufff0\013\ufff0\015\ufff0\016\ufff0\017\ufff0\020\ufff0\021\ufff0" +
    "\001\002\000\010\004\ufff5\006\041\011\040\001\002\000" +
    "\012\004\ufff2\005\023\006\036\011\035\001\002\000\012" +
    "\015\020\016\013\020\034\021\027\001\002\000\030\002" +
    "\uffec\004\uffec\006\uffec\010\uffec\011\uffec\013\uffec\015\uffec" +
    "\016\uffec\017\uffec\020\uffec\021\uffec\001\002\000\030\002" +
    "\uffed\004\uffed\006\uffed\010\uffed\011\uffed\013\uffed\015\uffed" +
    "\016\uffed\017\uffed\020\uffed\021\uffed\001\002\000\012\015" +
    "\020\016\013\020\034\021\027\001\002\000\030\002\uffe6" +
    "\004\uffe6\006\uffe6\010\uffe6\011\uffe6\013\uffe6\015\uffe6\016" +
    "\uffe6\017\uffe6\020\uffe6\021\uffe6\001\002\000\030\002\uffe7" +
    "\004\uffe7\006\uffe7\010\uffe7\011\uffe7\013\uffe7\015\uffe7\016" +
    "\uffe7\017\uffe7\020\uffe7\021\uffe7\001\002\000\012\015\020" +
    "\016\013\020\034\021\027\001\002\000\030\002\uffee\004" +
    "\uffee\006\uffee\010\uffee\011\uffee\013\uffee\015\uffee\016\uffee" +
    "\017\uffee\020\uffee\021\uffee\001\002\000\030\002\uffef\004" +
    "\uffef\006\uffef\010\uffef\011\uffef\013\uffef\015\uffef\016\uffef" +
    "\017\uffef\020\uffef\021\uffef\001\002\000\012\015\020\016" +
    "\013\020\034\021\027\001\002\000\030\002\uffea\004\uffea" +
    "\006\uffea\010\uffea\011\uffea\013\uffea\015\uffea\016\uffea\017" +
    "\uffea\020\uffea\021\uffea\001\002\000\030\002\uffeb\004\uffeb" +
    "\006\uffeb\010\uffeb\011\uffeb\013\uffeb\015\uffeb\016\uffeb\017" +
    "\uffeb\020\uffeb\021\uffeb\001\002\000\012\015\020\016\013" +
    "\020\022\021\010\001\002\000\030\002\uffdf\004\uffdf\006" +
    "\uffdf\010\uffdf\011\uffdf\013\uffdf\015\uffdf\016\uffdf\017\uffdf" +
    "\020\uffdf\021\uffdf\001\002\000\012\015\020\016\013\020" +
    "\034\021\027\001\002\000\030\002\uffe4\004\uffe4\006\uffe4" +
    "\010\uffe4\011\uffe4\013\uffe4\015\uffe4\016\uffe4\017\uffe4\020" +
    "\uffe4\021\uffe4\001\002\000\030\002\uffe5\004\uffe5\006\uffe5" +
    "\010\uffe5\011\uffe5\013\uffe5\015\uffe5\016\uffe5\017\uffe5\020" +
    "\uffe5\021\uffe5\001\002\000\012\015\020\016\013\020\034" +
    "\021\027\001\002\000\030\002\uffe8\004\uffe8\006\uffe8\010" +
    "\uffe8\011\uffe8\013\uffe8\015\uffe8\016\uffe8\017\uffe8\020\uffe8" +
    "\021\uffe8\001\002\000\030\002\uffe9\004\uffe9\006\uffe9\010" +
    "\uffe9\011\uffe9\013\uffe9\015\uffe9\016\uffe9\017\uffe9\020\uffe9" +
    "\021\uffe9\001\002\000\004\002\000\001\002\000\014\006" +
    "\064\015\020\016\013\020\065\021\027\001\002\000\004" +
    "\007\074\001\002\000\020\002\ufff0\004\ufff0\007\071\015" +
    "\ufff0\016\ufff0\020\ufff0\021\ufff0\001\002\000\012\004\ufff2" +
    "\005\023\006\067\011\066\001\002\000\012\015\020\016" +
    "\013\020\065\021\027\001\002\000\020\002\uffec\004\uffec" +
    "\007\ufffa\015\uffec\016\uffec\020\uffec\021\uffec\001\002\000" +
    "\004\007\ufffb\001\002\000\012\015\020\016\013\020\022" +
    "\021\010\001\002\000\006\004\051\010\073\001\002\000" +
    "\012\015\ufffc\016\ufffc\020\ufffc\021\ufffc\001\002\000\012" +
    "\015\020\016\013\020\022\021\010\001\002\000\006\004" +
    "\051\010\076\001\002\000\012\015\ufffd\016\ufffd\020\ufffd" +
    "\021\ufffd\001\002\000\012\015\020\016\013\020\022\021" +
    "\010\001\002\000\004\006\105\001\002\000\006\004\051" +
    "\013\103\001\002\000\004\006\uffe2\001\002\000\012\015" +
    "\020\016\013\020\022\021\010\001\002\000\006\004\051" +
    "\006\uffe1\001\002\000\012\015\020\016\013\020\022\021" +
    "\010\001\002\000\006\004\051\017\107\001\002\000\012" +
    "\015\020\016\013\020\022\021\010\001\002\000\030\002" +
    "\uffe3\004\051\006\uffe3\010\uffe3\011\uffe3\013\uffe3\015\uffe3" +
    "\016\uffe3\017\uffe3\020\uffe3\021\uffe3\001\002\000\004\002" +
    "\ufff9\001\002\000\004\002\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\110\000\024\002\016\003\003\004\004\006\010\007" +
    "\011\010\013\012\005\017\014\020\006\001\001\000\002" +
    "\001\001\000\022\003\111\004\004\006\010\007\011\010" +
    "\013\012\005\017\014\020\006\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\006\110\007\011\010\013\012\005\017\014\020\006" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\007\020" +
    "\010\013\012\005\017\014\020\006\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\007\025\010\027\011\030" +
    "\012\023\017\032\020\024\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\007\025\010\027\011\036" +
    "\012\023\017\032\020\024\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\007\025\010\027\011\041\012\023" +
    "\017\032\020\024\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\007\025\010\027\011\044\012\023\017\032" +
    "\020\024\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\007\025\010\027\011\047\012\023\017\032\020\024" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\007" +
    "\051\010\013\012\005\017\014\020\006\001\001\000\002" +
    "\001\001\000\016\007\025\010\027\011\054\012\023\017" +
    "\032\020\024\001\001\000\002\001\001\000\002\001\001" +
    "\000\016\007\025\010\027\011\057\012\023\017\032\020" +
    "\024\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\020\005\062\007\025\010\027\011\030\012" +
    "\023\017\032\020\024\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\005\067\007\025\010" +
    "\027\011\036\012\023\017\032\020\024\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\007\071\010\013\012" +
    "\005\017\014\020\006\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\007\074\010\013\012\005\017\014\020" +
    "\006\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\007\100\010\013\012\005\013\077\014\101\017\014\020" +
    "\006\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\007\103\010\013\012\005\017\014\020" +
    "\006\001\001\000\002\001\001\000\014\007\105\010\013" +
    "\012\005\017\014\020\006\001\001\000\002\001\001\000" +
    "\014\007\107\010\013\012\005\017\014\020\006\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserJava$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserJava$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserJava$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return s.next_token(); 
    }


    // Connect this parser to a scanner!
    Scanner s;
    ParserJava(Scanner s){ this.s=s; }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserJava$actions {
  private final ParserJava parser;

  /** Constructor */
  CUP$ParserJava$actions(ParserJava parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserJava$do_action_part00000000(
    int                        CUP$ParserJava$act_num,
    java_cup.runtime.lr_parser CUP$ParserJava$parser,
    java.util.Stack            CUP$ParserJava$stack,
    int                        CUP$ParserJava$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserJava$result;

      /* select the action based on the action number */
      switch (CUP$ParserJava$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // goal ::= startPoint 
            {
              String RESULT =null;
		int startleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int startright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String start = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 System.out.println("public class Translated {\n" + start + "\n}"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("goal",0, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= goal EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		RESULT = start_val;
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserJava$parser.done_parsing();
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // startPoint ::= functionDefinition startPoint 
            {
              String RESULT =null;
		int funDefleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int funDefright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String funDef = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int startleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int startright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String start = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = funDef + "\n" + start; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("startPoint",1, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // startPoint ::= continue 
            {
              String RESULT =null;
		int cnleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int cnright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String cn = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = "public static void main(String[] args) {\n" + cn + "}\n"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("startPoint",1, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // functionDefinition ::= IDENTIFIER LPAREN functionDefArgs LBRACE exprList RBRACE 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)).value;
		int lparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).left;
		int lparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).right;
		String lpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).value;
		int funcDefArgsleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).left;
		int funcDefArgsright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).right;
		String funcDefArgs = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).value;
		int lbracleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int lbracright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String lbrac = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int expLleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int expLright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String expL = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int rbracleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int rbracright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String rbrac = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = "public static String " + id + "( " + funcDefArgs + "\n{\n\t return " + expL + ";\n}"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionDefinition",2, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // functionDefinition ::= IDENTIFIER LPAREN RPAREN LBRACE exprList RBRACE 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)).value;
		int lparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).left;
		int lparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).right;
		String lpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).value;
		int rparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).left;
		int rparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).right;
		String rpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).value;
		int lbracleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int lbracright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String lbrac = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int expLleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int expLright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String expL = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int rbracleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int rbracright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String rbrac = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = "public static String "+ id +"()\n{\n\t return "+ expL +";\n}"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionDefinition",2, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // functionDefArgs ::= IDENTIFIER COMMA functionDefArgs 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int comleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int comright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String com = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int funcDefArgsleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int funcDefArgsright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String funcDefArgs = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = "String " + id + " " + com + " " + funcDefArgs + " "; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionDefArgs",3, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // functionDefArgs ::= IDENTIFIER RPAREN 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int rparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int rparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String rpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = "String " + id + ")"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionDefArgs",3, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // continue ::= exprList continue 
            {
              String RESULT =null;
		int expLleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int expLright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String expL = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int cnleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int cnright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String cn = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		RESULT = "System.out.println( " + expL + " );\n" + cn + " \n"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("continue",4, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // continue ::= exprList 
            {
              String RESULT =null;
		int expLleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int expLright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String expL = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		RESULT = "System.out.println( " + expL + " );"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("continue",4, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // exprList ::= conditional 
            {
              String RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int condright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = "(" + cond + ")"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("exprList",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // exprList ::= concatenation 
            {
              String RESULT =null;
		int concatleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int concatright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String concat = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = "(" + concat + ")"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("exprList",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // exprList ::= reversion 
            {
              String RESULT =null;
		int revleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int revright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String rev = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = "(" + rev + ")"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("exprList",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // exprList ::= functionCall 
            {
              String RESULT =null;
		int funcCallleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int funcCallright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String funcCall = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = "(" + funcCall + ")"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("exprList",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // exprList ::= STRING 
            {
              String RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String str = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = "(" + str + ")"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("exprList",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // exprList ::= IDENTIFIER 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = "(" + id + ")"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("exprList",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // functionCall ::= IDENTIFIER LPAREN functionCallArgs 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int lparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int lparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String lpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int funcCallArgsleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int funcCallArgsright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String funcCallArgs = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = id + " " + lpar + " " + funcCallArgs; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCall",6, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // functionCall ::= IDENTIFIER LPAREN RPAREN 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int lparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int lparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String lpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int rparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int rparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String rpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = id + " " + lpar + " " + rpar; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCall",6, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // functionCallArgs ::= functionCall COMMA functionCallArgs 
            {
              String RESULT =null;
		int funcCallleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int funcCallright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String funcCall = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int comleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int comright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String com = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int funcCallArgsleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int funcCallArgsright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String funcCallArgs = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = funcCall + " " + com + " " + funcCallArgs; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // functionCallArgs ::= functionCall RPAREN 
            {
              String RESULT =null;
		int funcCallleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int funcCallright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String funcCall = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int rparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int rparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String rpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = funcCall + " " + rpar; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // functionCallArgs ::= IDENTIFIER COMMA functionCallArgs 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int comleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int comright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String com = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int funcCallArgsleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int funcCallArgsright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String funcCallArgs = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = id + " " + com + " " + funcCallArgs; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // functionCallArgs ::= IDENTIFIER RPAREN 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int rparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int rparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String rpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = id + " " + rpar; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // functionCallArgs ::= STRING COMMA functionCallArgs 
            {
              String RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String str = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int comleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int comright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String com = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int funcCallArgsleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int funcCallArgsright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String funcCallArgs = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = str + " " + com + " " + funcCallArgs; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // functionCallArgs ::= STRING RPAREN 
            {
              String RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int strright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String str = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int rparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int rparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String rpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = str + " " + rpar; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // functionCallArgs ::= conditional COMMA functionCallArgs 
            {
              String RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int comleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int comright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String com = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int funcCallArgsleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int funcCallArgsright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String funcCallArgs = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = cond + " " + com + " " + funcCallArgs; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // functionCallArgs ::= conditional RPAREN 
            {
              String RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String cond = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int rparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int rparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String rpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = cond + " " + rpar; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // functionCallArgs ::= reversion COMMA functionCallArgs 
            {
              String RESULT =null;
		int revleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int revright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String rev = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int comleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int comright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String com = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int funcCallArgsleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int funcCallArgsright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String funcCallArgs = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = rev + " " + com + " " + funcCallArgs; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // functionCallArgs ::= reversion RPAREN 
            {
              String RESULT =null;
		int revleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int revright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String rev = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int rparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int rparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String rpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = rev + " " + rpar; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // functionCallArgs ::= concatenation COMMA functionCallArgs 
            {
              String RESULT =null;
		int concatleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int concatright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String concat = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int comleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int comright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String com = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int funcCallArgsleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int funcCallArgsright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String funcCallArgs = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = concat + " " + com + " " + funcCallArgs; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // functionCallArgs ::= concatenation RPAREN 
            {
              String RESULT =null;
		int concatleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int concatright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String concat = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int rparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int rparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String rpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = concat + " " + rpar; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("functionCallArgs",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // conditional ::= IF LPAREN exprCon RPAREN exprList ELSE exprList 
            {
              String RESULT =null;
		int if1left = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-6)).left;
		int if1right = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-6)).right;
		String if1 = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-6)).value;
		int lparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)).left;
		int lparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)).right;
		String lpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)).value;
		int expCleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).left;
		int expCright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).right;
		String expC = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).value;
		int rparleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).left;
		int rparright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).right;
		String rpar = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).value;
		int expLleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int expLright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String expL = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int else1left = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int else1right = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String else1 = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int expL2left = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int expL2right = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String expL2 = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		RESULT ="("+ expC +")?("+ expL +"):("+ expL2 +")"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("conditional",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-6)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // exprCon ::= prefix 
            {
              String RESULT =null;
		int prefleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int prefright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String pref = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = pref; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("exprCon",9, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // prefix ::= exprList PREF exprList 
            {
              String RESULT =null;
		int expLleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int expLright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String expL = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int prefleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int prefright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String pref = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int expL2left = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int expL2right = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String expL2 = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = expL2 + ".startsWith(" + expL + ")"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("prefix",10, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // reversion ::= REVERSE exprList 
            {
              String RESULT =null;
		int revleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int revright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String rev = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int expLleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int expLright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String expL = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		RESULT ="new StringBuilder(" + expL + ").reverse().toString()"; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("reversion",13, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // concatenation ::= exprList CONCAT exprList 
            {
              String RESULT =null;
		int expLleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).left;
		int expLright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).right;
		String expL = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)).value;
		int concatleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int concatright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		String concat = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		int expL2left = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).left;
		int expL2right = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()).right;
		String expL2 = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.peek()).value;
		 RESULT = expL + " " + concat + " " + expL2; 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("concatenation",14, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserJava$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserJava$do_action(
    int                        CUP$ParserJava$act_num,
    java_cup.runtime.lr_parser CUP$ParserJava$parser,
    java.util.Stack            CUP$ParserJava$stack,
    int                        CUP$ParserJava$top)
    throws java.lang.Exception
    {
              return CUP$ParserJava$do_action_part00000000(
                               CUP$ParserJava$act_num,
                               CUP$ParserJava$parser,
                               CUP$ParserJava$stack,
                               CUP$ParserJava$top);
    }
}

}
