run: compile execute

compile:
	javac Main.java ParseError.java Parser.java

execute:
# 1st test
# echo "(2+3**3)+2+4" | java Main
# 2nd test
# echo "3-2**7+3-12+(4+3-5)**1+0-1+1" | java Main
# 3rd test
	echo "3+(5+2+1)-(5-2-(3))" | java Main